version: '3'
services:
  db:
    image: postgres
    networks:
      - default
    volumes:
      - psql-data:/var/lib/postgresql/data

  redis:
    image: redis
    networks:
      - default
    volumes:
      - redis-data:/data

  web:
    build:
      context: .
      dockerfile: Dockerfile-dev
    # Enable sending signals (CTRL+C, CTRL+P + CTRL+Q) into the container:
    tty: true
    # Keep the stdin open, so we can attach to our app container's process and do things such as byebug, etc:
    stdin_open: true
    networks:
      - default
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
      - bundle_cache:/app/vendor/bundle
      - bundle:/app/.bundle

volumes:
  psql-data:
    driver: local
  redis-data:
    driver: local
  bundle_install:
    driver: local
  bundle:
    driver: local
