version: '3.4'
services:
  db:
    image: postgres:alpine
    volumes:
      - ./tmp/srv/app/db:/var/lib/postgresql/data

  app: &app_base
    build:
      context: .
      dockerfile: Dockerfile
    # Enable sending signals (CTRL+C, CTRL+P + CTRL+Q) into the container:
    tty: true
    # Keep the stdin open, so we can attach to our app container's process and do things such as byebug, etc:
    stdin_open: true
    command:
      - /bin/sh
      - -c
      - |
        if [ -f tmp/pids/server.pid ]; then
          rm -f tmp/pids/server.pid
        fi
        bundle exec rails s -p 3000 -b 0.0.0.0
    volumes:
      - .:/app
    ports:
      - 3000:3000
    links:
      - db
